### ISSUE TITLE
Gazebo5 ros pkgs 2.4.9

### ISSUE THREAD

**Issue by jvgomez** [osrf/gazebo5_ros_pkgs-release#2]
Hi,

I saw that gazebo_ros_pkgs 2.4.9 were released today, but I cannot install them as they require Gazebo2 and I am using Gazebo5. Could you please release the gazebo5_ros_pkgs 2.4.9?

Thank you!!

**Comment by j-rivero** [comment]
Hey Javi!

> I saw that gazebo_ros_pkgs 2.4.9 were released today, but I cannot install them as they require Gazebo2 and I am using Gazebo5.

I assume that you are using Indigo, right?

> Could you please release the gazebo5_ros_pkgs 2.4.9?

I can give it a look for 2.4.9 indigo gazebo5 wrappers, yes.

**Comment by jvgomez** [comment]
Hey Jose! Nice to talk to you :)
Yes, Indigo I forgot to mention.
Thank you so much for your help!

**Comment by j-rivero** [comment]
2.4.9 gazebo5 Indigo packages are in the osrf repository. Javi let me know if they work for you or you find any problem.

**Comment by jvgomez** [comment]
@j-rivero It works fine, thank you so much!
